#!/bin/bash

#cd -- $(dirname $BASH_SOURCE)

jx=$(which java)

echo pwd 1: $(pwd)
cd $(dirname $0)
echo pwd 2: $(pwd)

$jx -version

$jx --enable-native-access=ALL-UNNAMED -cp "lib/*" com.femtioprocent.omega.appl.Omega_IS "$@"
